#!/usr/bin/env python3
"""Compare the retained Settings Home implementation with the live UI probes.

This parser is read-only. It does not connect to ADB and does not infer a
PackageManager or framework change from a Settings resource difference.
"""

from __future__ import annotations

import argparse
import hashlib
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path


ANDROID_NS = "{http://schemas.android.com/apk/res/android}"
HOME_KEY = "default_home"
HOME_TEXTS = ("Home app", "ホームアプリ", "Home")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--installed-xml", required=True, type=Path)
    parser.add_argument("--aosp-xml", action="append", required=True, type=Path)
    parser.add_argument("--live-ui", action="append", required=True, type=Path)
    parser.add_argument("--activity", action="append", default=[], type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--dry-run", action="store_true")
    return parser.parse_args()


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def parse_xml(path: Path) -> ET.Element:
    try:
        return ET.parse(path).getroot()
    except ET.ParseError as exc:
        raise ValueError(f"invalid XML: {path}: {exc}") from exc


def resource_keys(root: ET.Element) -> set[str]:
    keys: set[str] = set()
    for element in root.iter():
        key = element.attrib.get(ANDROID_NS + "key")
        if key:
            keys.add(key)
    return keys


def ui_texts(root: ET.Element) -> list[str]:
    values = []
    for element in root.iter():
        text = element.attrib.get("text", "").strip()
        if text:
            values.append(text)
    return values


def has_home_text(values: list[str]) -> bool:
    return any(any(token in value for token in HOME_TEXTS) for value in values)


def resumed_activity(path: Path) -> str:
    pattern = re.compile(r"(?:mResumedActivity|ResumedActivity):.*? u\d+ ([^\s}]+)")
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        match = pattern.search(line)
        if match:
            return match.group(1)
    return "not found"


def display(path: Path) -> str:
    try:
        return str(path.resolve().relative_to(Path.cwd().resolve()))
    except ValueError:
        return str(path.resolve())


def main() -> int:
    args = parse_args()
    inputs = [args.installed_xml, *args.aosp_xml, *args.live_ui, *args.activity]
    missing = [path for path in inputs if not path.is_file()]
    if missing:
        for path in missing:
            print(f"input is not a file: {path}", file=sys.stderr)
        return 2
    if args.output.exists():
        print(f"refusing to overwrite existing output: {args.output}", file=sys.stderr)
        return 2
    if args.dry_run:
        print("DRY-RUN: no XML will be parsed and no output will be written.")
        print(f"DRY-RUN: installed={args.installed_xml} aosp={len(args.aosp_xml)} live_ui={len(args.live_ui)} output={args.output}")
        return 0

    try:
        installed_root = parse_xml(args.installed_xml)
        aosp = [(path, parse_xml(path)) for path in args.aosp_xml]
        live = [(path, parse_xml(path)) for path in args.live_ui]
    except ValueError as exc:
        print(str(exc), file=sys.stderr)
        return 2

    installed_keys = resource_keys(installed_root)
    installed_has_home = HOME_KEY in installed_keys
    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", encoding="utf-8") as handle:
        handle.write("# Settings Home UI analysis\n\n")
        handle.write("This output is generated by `tools/scripts/analyze_settings_home_ui.py`; it is a resource/UI comparison, not proof of a PackageManager patch.\n\n")
        handle.write("## Static resource comparison\n\n")
        handle.write("| Source | `default_home` key | SHA-256 |\n|---|---:|---|\n")
        handle.write(f"| `{display(args.installed_xml)}` | {'present' if installed_has_home else 'absent'} | `{sha256(args.installed_xml)}` |\n")
        for path, root in aosp:
            handle.write(f"| `{display(path)}` | {'present' if HOME_KEY in resource_keys(root) else 'absent'} | `{sha256(path)}` |\n")
        handle.write("\n## Live UI probes\n\n")
        handle.write("| Probe UI file | Home-app text present | SHA-256 |\n|---|---:|---|\n")
        for path, root in live:
            texts = ui_texts(root)
            handle.write(f"| `{display(path)}` | {'yes' if has_home_text(texts) else 'no'} | `{sha256(path)}` |\n")
        if args.activity:
            handle.write("\n## Resumed activities\n\n")
            handle.write("| Snapshot | Resumed activity | SHA-256 |\n|---|---|---|\n")
            for path in args.activity:
                handle.write(f"| `{display(path)}` | `{resumed_activity(path)}` | `{sha256(path)}` |\n")
        handle.write("\n## Interpretation\n\n")
        if not installed_has_home and any(HOME_KEY in resource_keys(root) for _, root in aosp):
            handle.write("- `Confirmed`: the installed main Default apps XML omits `default_home` while the supplied AOSP reference XML includes it.\n")
        if live and all(not has_home_text(ui_texts(root)) for _, root in live):
            handle.write("- `Confirmed for supplied UI dumps`: no supplied live UI dump contains a Home-app label.\n")
        handle.write("- The output does not assert why PackageManager selected a HOME activity; consult resolver and framework evidence separately.\n")
    print(f"generated {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
