flowchart LR
  base["base"] -->|vendor_service| com_amazon_android_server_am_AmazonActivityManagerService["com.amazon.android.server.am.AmazonActivityManagerService"]
  com_android_server_am_VendorActivityRecordCallback["com.android.server.am.VendorActivityRecordCallback"] -->|callback| com_amazon_android_server_am_OnConfigurationChanged["com.amazon.android.server.am.OnConfigurationChanged"]
  com_android_server_am_VendorActivityManagerServiceCallback["com.android.server.am.VendorActivityManagerServiceCallback"] -->|callback| com_android_server_am_AmazonActivityManagerAMSCallback["com.android.server.am.AmazonActivityManagerAMSCallback"]
  com_android_server_dreams_VendorDreamControllerCallback["com.android.server.dreams.VendorDreamControllerCallback"] -->|callback| com_android_server_am_AmazonDreamControllerCallback["com.android.server.am.AmazonDreamControllerCallback"]
  base["base"] -->|vendor_service| com_amazon_android_server_devicepolicy_AmazonDevicePolicyManagerServic["com.amazon.android.server.devicepolicy.AmazonDevicePolicyManagerService"]
  com_android_server_devicepolicy_VendorDevicePolicyManagerCallback["com.android.server.devicepolicy.VendorDevicePolicyManagerCallback"] -->|callback| amazon_app_admin_AmazonDevicePolicyManagerCallback["amazon.app.admin.AmazonDevicePolicyManagerCallback"]
  com_android_server_pm_VendorUserRestrictionsUtilsCallback["com.android.server.pm.VendorUserRestrictionsUtilsCallback"] -->|callback| amazon_app_admin_DevicePolicyManagerUserRestrictionsCallback["amazon.app.admin.DevicePolicyManagerUserRestrictionsCallback"]
  com_android_server_pm_VendorPackageManagerCallback["com.android.server.pm.VendorPackageManagerCallback"] -->|callback| com_amazon_android_server_devicepolicy_DevicePolicySystemOtaHandlerCal["com.amazon.android.server.devicepolicy.DevicePolicySystemOtaHandlerCallback"]
  base["base"] -->|vendor_service| com_amazon_android_service_pm_AmazonPackageManagerService["com.amazon.android.service.pm.AmazonPackageManagerService"]
  com_android_server_pm_VendorPackageManagerCallback["com.android.server.pm.VendorPackageManagerCallback"] -->|callback| com_amazon_android_service_pm_PermissionToUsesPermissionCallback["com.amazon.android.service.pm.PermissionToUsesPermissionCallback"]
  com_android_server_pm_VendorPackageManagerCallback["com.android.server.pm.VendorPackageManagerCallback"] -->|callback| com_amazon_android_service_pm_AmazonPackageManagerCallback["com.amazon.android.service.pm.AmazonPackageManagerCallback"]
  com_android_server_pm_VendorPackageManagerCallback["com.android.server.pm.VendorPackageManagerCallback"] -->|callback| com_amazon_android_service_pm_CleanUpDalvikCacheCallback["com.amazon.android.service.pm.CleanUpDalvikCacheCallback"]
  com_android_server_pm_VendorProtectedPackagesCallback["com.android.server.pm.VendorProtectedPackagesCallback"] -->|callback| com_amazon_android_service_pm_ControlProtectedPackagesCallback["com.amazon.android.service.pm.ControlProtectedPackagesCallback"]
  android_content_pm_PackageManager["android.content.pm.PackageManager"] -->|vendor_instance| amazon_content_pm_AmazonPackageManagerImpl["amazon.content.pm.AmazonPackageManagerImpl"]
  android_content_pm_PackageStats["android.content.pm.PackageStats"] -->|vendor_instance| amazon_content_pm_AmazonPackageStats["amazon.content.pm.AmazonPackageStats"]
  base["base"] -->|vendor_service| com_amazon_android_server_wm_AmazonWindowManagerService["com.amazon.android.server.wm.AmazonWindowManagerService"]
  com_android_server_policy_VendorPhoneWindowManagerCallback["com.android.server.policy.VendorPhoneWindowManagerCallback"] -->|callback| com_android_server_policy_AmazonWindowManagerPwmCallback["com.android.server.policy.AmazonWindowManagerPwmCallback"]
  com_android_server_wm_VendorWindowManagerServiceCallback["com.android.server.wm.VendorWindowManagerServiceCallback"] -->|callback| com_android_server_wm_AmazonVendorWindowManagerServiceCallback["com.android.server.wm.AmazonVendorWindowManagerServiceCallback"]
  com_android_server_wm_VendorAppTransitionCallback["com.android.server.wm.VendorAppTransitionCallback"] -->|callback| com_android_server_wm_AmazonVendorAppTransitionCallback["com.android.server.wm.AmazonVendorAppTransitionCallback"]
  android_view_VendorViewRootImplCallback["android.view.VendorViewRootImplCallback"] -->|callback| amazon_view_AmazonVendorViewRootImplCallback["amazon.view.AmazonVendorViewRootImplCallback"]
  base["base"] -->|vendor_service| com_amazon_appcompatwhitelist_AppCompatWhitelistService["com.amazon.appcompatwhitelist.AppCompatWhitelistService"]
  com_android_server_am_VendorActivityManagerServiceCallback["com.android.server.am.VendorActivityManagerServiceCallback"] -->|callback| com_android_server_am_AppCompatActivityManagerServiceCallback["com.android.server.am.AppCompatActivityManagerServiceCallback"]
  com_android_server_am_VendorActivityStackSupervisorCallback["com.android.server.am.VendorActivityStackSupervisorCallback"] -->|callback| com_amazon_android_server_am_AppCompatActivityStackSupervisorCallback["com.amazon.android.server.am.AppCompatActivityStackSupervisorCallback"]
  com_android_server_am_VendorActivityStarterCallback["com.android.server.am.VendorActivityStarterCallback"] -->|callback| com_amazon_android_server_am_AppCompatActivityStarterCallback["com.amazon.android.server.am.AppCompatActivityStarterCallback"]
  com_amazon_android_appcompatsupport_AppCompatSupport["com.amazon.android.appcompatsupport.AppCompatSupport"] -->|vendor_instance| com_amazon_android_appcompatsupport_AppCompatSupportImpl["com.amazon.android.appcompatsupport.AppCompatSupportImpl"]
  com_android_server_VendorSystemServerCallback["com.android.server.VendorSystemServerCallback"] -->|callback| com_amazon_android_server_InitFireOsSystemConfigCallback["com.amazon.android.server.InitFireOsSystemConfigCallback"]
  base["base"] -->|vendor_service| amazon_fireos_debug_FireOSDebugService["amazon.fireos.debug.FireOSDebugService"]
  com_android_server_am_VendorActivityStackCallback["com.android.server.am.VendorActivityStackCallback"] -->|callback| com_android_server_am_EveActivityStackCallback["com.android.server.am.EveActivityStackCallback"]
  com_android_server_am_VendorActivityStackSupervisorCallback["com.android.server.am.VendorActivityStackSupervisorCallback"] -->|callback| com_fireos_eve_EveActivityStackSupervisorCallback["com.fireos.eve.EveActivityStackSupervisorCallback"]
  com_android_server_am_VendorActivityRecordCallback["com.android.server.am.VendorActivityRecordCallback"] -->|callback| com_android_server_am_EveActivityRecordCallback["com.android.server.am.EveActivityRecordCallback"]
  com_android_server_am_VendorActivityStarterCallback["com.android.server.am.VendorActivityStarterCallback"] -->|callback| com_fireos_eve_EveActivityStarterCallback["com.fireos.eve.EveActivityStarterCallback"]
  android_app_VendorActivityThreadCallback["android.app.VendorActivityThreadCallback"] -->|callback| com_fireos_eve_EveActivityThreadCallback["com.fireos.eve.EveActivityThreadCallback"]
  com_android_providers_settings_VendorSettingsProviderCallback["com.android.providers.settings.VendorSettingsProviderCallback"] -->|callback| com_amazon_android_settings_keypolicymanager_KeyPolicyManagerSettingsP["com.amazon.android.settings.keypolicymanager.KeyPolicyManagerSettingsProvider"]
  com_android_server_am_VendorActivityStackCallback["com.android.server.am.VendorActivityStackCallback"] -->|callback| com_amazon_launcherhijackpreventer_LauncherHijackPreventerActivityStac["com.amazon.launcherhijackpreventer.LauncherHijackPreventerActivityStackCallback"]
  com_android_server_am_VendorActivityManagerServiceCallback["com.android.server.am.VendorActivityManagerServiceCallback"] -->|callback| com_amazon_launcherhijackpreventer_LauncherHijackPreventerActivityMana["com.amazon.launcherhijackpreventer.LauncherHijackPreventerActivityManagerServiceCallback"]
  com_android_server_pm_VendorPackageManagerCallback["com.android.server.pm.VendorPackageManagerCallback"] -->|callback| com_android_server_pm_PackageWhitelisterCallback["com.android.server.pm.PackageWhitelisterCallback"]
  com_amazon_android_keypolicymanager_KeyPolicyManager["com.amazon.android.keypolicymanager.KeyPolicyManager"] -->|vendor_instance| com_amazon_policy_keypolicymanager_TabletKeyPolicyManager["com.amazon.policy.keypolicymanager.TabletKeyPolicyManager"]
  com_android_server_policy_VendorPhoneWindowManagerCallback["com.android.server.policy.VendorPhoneWindowManagerCallback"] -->|callback| com_amazon_policy_keypolicymanager_KeyInterceptorCallback["com.amazon.policy.keypolicymanager.KeyInterceptorCallback"]
  com_android_server_pm_VendorPackageManagerCallback["com.android.server.pm.VendorPackageManagerCallback"] -->|callback| com_amazon_launcherhijackpreventer_LauncherHijackPreventerPackageManag["com.amazon.launcherhijackpreventer.LauncherHijackPreventerPackageManagerCallback"]
  com_android_server_pm_permission_VendorPermissionManagerCallback["com.android.server.pm.permission.VendorPermissionManagerCallback"] -->|callback| com_amazon_launcherhijackpreventer_LauncherHijackPreventerPermissionMa["com.amazon.launcherhijackpreventer.LauncherHijackPreventerPermissionManagerCallback"]
